---
apiVersion: v1
kind: Namespace
metadata:
  name: aws9f
---
#blog svc
apiVersion: v1
kind: Service
metadata:
  name: aws9-svc-blog
  namespace: aws9f
spec:
  selector:
    web: blog-svc
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
#blog deploy
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: blog-deploy
  namespace: aws9f
spec:
  selector:
    matchLabels:
      web: blog-svc
  template:
    metadata: 
      labels:
        web: blog-svc
    spec:
      containers:
      - name: blogctn
        image: hub.aws9.pri/aws9/blog:1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 80   