---
#blog svc
apiVersion: v1
kind: Service
metadata:
  name: aws9-svc-blog
spec:
  selector:
    web: blog-svc
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
#blog deploy
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: blog-deploy
spec:
  selector:
    matchLabels:
      web: blog-svc
  template:
    metadata: 
      labels:
        web: blog-svc
    spec:
      containers:
      - name: blogctn
        image: shjtest/aws:green
        ports:
          - containerPort: 80   